import '../styles/globals.scss';
import '../styles/tailwind.css';

import type { Metadata } from 'next';
import { JSX } from 'react';

export const metadata: Metadata = {
    title: 'SpeechCare',
    description: 'Generated by create next app',
    icons: {
        icon: '/favicon.ico',
    },
};

export default function RootLayout({
    children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
    return (
        <html lang="es">
            <body>
                <main>{children}</main>
            </body>
        </html>
    );
}

