#!/usr/bin/env sh

# sort locales
for file in src/i18n/locales/*.json; do
  jq -r -s --sort-keys 'sort_by(.key) | .[]' "$file" > "$file.tmp" && mv "$file.tmp" "$file"
  git add "$file"
done

# npm test
npm run lint || exit 1
npm run test || exit 1

